# Generated by Django 2.2 on 2021-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortinas', '0003_auto_20210502_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
